"""
Gelato Print API Service — v3
Handles order creation, status queries and cancellation.

Gelato v3 docs: https://dashboard.gelato.com/docs/orders/v3/
Auth: X-API-KEY header (no OAuth needed).

Environment variables:
  GELATO_API_KEY        — production or sandbox key
  GELATO_USE_SANDBOX    — "true" to skip real fulfilment (default "true")
  GELATO_WEBHOOK_SECRET — shared secret to verify webhook signatures (optional)
  APP_BASE_URL          — public HTTPS base URL of this Flask app
                          e.g. https://magicmemoriesbooks.com
                          Used to build the PDF download URL sent to Gelato.
"""

import os
import hmac
import hashlib
import uuid
import concurrent.futures
import requests
from typing import Optional

GELATO_API_BASE = "https://order.gelatoapis.com"

HC_A4_SKU = (
    "photobooks-hardcover_pf_210x280-mm-8x11-inch"
    "_pt_170-gsm-65lb-coated-silk"
    "_cl_4-4_ccl_4-4_bt_glued-left_ct_matt-lamination"
    "_prt_1-0_cpt_130-gsm-65-lb-cover-coated-silk_ver"
)

STATUS_TRANSLATIONS = {
    "created":    {"es": "Pedido recibido",      "en": "Order received"},
    "passed":     {"es": "En producción",        "en": "In production"},
    "failed":     {"es": "Error en el pedido",   "en": "Order failed"},
    "canceled":   {"es": "Pedido cancelado",     "en": "Order cancelled"},
    "printed":    {"es": "Imprimiendo",          "en": "Printing"},
    "shipped":    {"es": "Enviado",              "en": "Shipped"},
    "delivered":  {"es": "Entregado",            "en": "Delivered"},
    "returned":   {"es": "Devuelto",             "en": "Returned"},
    "draft":      {"es": "Borrador",             "en": "Draft"},
}


def _get_api_key() -> str:
    key = os.environ.get("GELATO_API_KEY", "")
    if not key:
        raise RuntimeError("GELATO_API_KEY environment variable is not set")
    return key


def _headers() -> dict:
    return {
        "X-API-KEY": _get_api_key(),
        "Content-Type": "application/json",
    }


def _app_base_url() -> str:
    url = os.environ.get("APP_BASE_URL", "").rstrip("/")
    if not url:
        domain = os.environ.get("REPLIT_DEV_DOMAIN", "")
        if domain:
            url = f"https://{domain}"
    return url


def build_pdf_url(session_id: str, filename: str = "combined_34p.pdf") -> str:
    """
    Build a publicly accessible HTTPS URL for a Gelato PDF file.
    Uses the Flask /preview-pdf/gelato/<session_id>/<filename> route.

    Default is the combined 34-page PDF (cover wrap + interior + end papers).
    """
    base = _app_base_url()
    if not base:
        raise RuntimeError(
            "Cannot build PDF URL: APP_BASE_URL or REPLIT_DEV_DOMAIN not set"
        )
    return f"{base}/preview-pdf/gelato/{session_id}/{filename}"


def build_cover_url(session_id: str, filename: str = "cover_wrap.pdf") -> str:
    """Build a publicly accessible HTTPS URL for the cover wrap PDF (kept for reference)."""
    base = _app_base_url()
    if not base:
        raise RuntimeError(
            "Cannot build cover URL: APP_BASE_URL or REPLIT_DEV_DOMAIN not set"
        )
    return f"{base}/preview-pdf/gelato/{session_id}/{filename}"


def create_order(
    order_reference_id: str,
    customer_name: str,
    customer_email: str,
    shipping_address: dict,
    combined_pdf_url: str,
    interior_pdf_url: str = None,  # kept for backwards compat, ignored
    cover_pdf_url: str = None,     # kept for backwards compat, ignored
    quantity: int = 1,
    sku: str = HC_A4_SKU,
    currency: str = "USD",
    dry_run: bool = None,
    shipment_method_uid: str = "express",
) -> Optional[dict]:
    """
    Submit a print order to Gelato v3.

    Gelato photobooks require a single combined PDF containing:
      Page 1     : Cover wrap (478×326mm full spread with bleed)
      Page 2     : Blank end paper (inside front cover)
      Pages 3-32 : 30 interior pages
      Pages 33-34: Blank end papers (inside back cover)

    Args:
        order_reference_id: Your internal order ID (e.g. 'ORD-12345')
        customer_name:      Full name of the recipient
        customer_email:     Customer email for Gelato notifications
        shipping_address:   Dict with keys: address_line1, address_line2,
                            city, state, post_code, country, phone
        combined_pdf_url:   Public HTTPS URL to the combined 34-page PDF
                            (generated by gelato_combined_pdf_service)
        quantity:           Number of copies (default 1)
        sku:                Gelato product SKU (default HC A4 210×280mm)
        currency:           ISO currency code (default USD)
        dry_run:            If True, creates a draft order (not printed).
                            Defaults to GELATO_USE_SANDBOX env var.

    Returns:
        Gelato order response dict, or None on failure.
    """
    if dry_run is None:
        dry_run = os.environ.get("GELATO_USE_SANDBOX", "true").lower() == "true"

    url = f"{GELATO_API_BASE}/v3/orders"

    payload = {
        "orderType": "order",
        "orderReferenceId": order_reference_id,
        "customerReferenceId": order_reference_id,
        "currency": currency,
        "items": [
            {
                "itemReferenceId": f"{order_reference_id}-1",
                "productUid": sku,
                "quantity": quantity,
                "pageCount": 30,       # interior page count (Gelato adds 4 for covers = 34 total)
                "fileUrl": combined_pdf_url,   # single combined PDF (34 pages)
            }
        ],
        "shipmentMethodUid": shipment_method_uid,
        "shippingAddress": {
            "firstName": customer_name.split()[0] if customer_name else "",
            "lastName":  " ".join(customer_name.split()[1:]) if customer_name else "",
            "addressLine1": shipping_address.get("address_line1", ""),
            "addressLine2": shipping_address.get("address_line2", ""),
            "city":        shipping_address.get("city", ""),
            "state":       shipping_address.get("state", ""),
            "postCode":    shipping_address.get("post_code") or shipping_address.get("postal_code", ""),
            "country":     shipping_address.get("country", "US"),
            "email":       customer_email,
            "phone":       shipping_address.get("phone", ""),
        },
        "metadata": [],
    }

    if dry_run:
        payload["orderType"] = "draft"
        print(f"[GELATO API] DRY RUN — order will be created as draft (not printed)")

    print(f"[GELATO API] Creating order: {order_reference_id}")
    print(f"[GELATO API] Combined PDF (34 pages): {combined_pdf_url}")

    try:
        response = requests.post(url, headers=_headers(), json=payload, timeout=60)
        if response.status_code in (200, 201):
            data = response.json()
            print(f"[GELATO API] Order created: {data.get('id')}, status: {data.get('status')}")
            return data
        else:
            print(f"[GELATO API] Order creation failed: {response.status_code}")
            print(f"[GELATO API] Response: {response.text[:1000]}")
            return None
    except Exception as e:
        print(f"[GELATO API] Error creating order: {e}")
        return None


def get_order_status(gelato_order_id: str) -> Optional[dict]:
    """
    Retrieve the current status of a Gelato order.

    Returns dict with keys:
      status, status_text (es/en), tracking_code, tracking_url, carrier
    """
    url = f"{GELATO_API_BASE}/v3/orders/{gelato_order_id}"

    try:
        response = requests.get(url, headers=_headers(), timeout=30)
        if response.status_code == 200:
            data = response.json()
            status = data.get("fulfillmentStatus") or data.get("status", "unknown")
            shipments = data.get("shipments", [])
            tracking_code = None
            tracking_url = None
            carrier = None
            if shipments:
                s = shipments[0]
                tracking_code = s.get("trackingCode")
                tracking_url = s.get("trackingUrl")
                carrier = s.get("carrier")

            result = {
                "status": status,
                "status_text": STATUS_TRANSLATIONS.get(status, {"es": status, "en": status}),
                "tracking_code": tracking_code,
                "tracking_url": tracking_url,
                "carrier": carrier,
                "raw": data,
            }
            print(f"[GELATO API] Order {gelato_order_id} status: {status}")
            return result
        else:
            print(f"[GELATO API] Status check failed: {response.status_code} — {response.text[:300]}")
            return None
    except Exception as e:
        print(f"[GELATO API] Error getting order status: {e}")
        return None


def cancel_order(gelato_order_id: str) -> bool:
    """
    Cancel a Gelato order. Only works while status is 'created' or 'draft'.
    Returns True if successfully cancelled.
    """
    url = f"{GELATO_API_BASE}/v3/orders/{gelato_order_id}"

    try:
        response = requests.delete(url, headers=_headers(), timeout=30)
        if response.status_code in (200, 204):
            print(f"[GELATO API] Order {gelato_order_id} cancelled")
            return True
        else:
            print(f"[GELATO API] Cancel failed: {response.status_code} — {response.text[:300]}")
            return False
    except Exception as e:
        print(f"[GELATO API] Error cancelling order: {e}")
        return False


def verify_webhook_signature(payload_bytes: bytes, signature_header: str) -> bool:
    """
    Verify a Gelato webhook signature.
    Gelato signs with HMAC-SHA256 using the webhook secret.
    Returns True if the signature matches.
    """
    secret = os.environ.get("GELATO_WEBHOOK_SECRET", "")
    if not secret:
        print("[GELATO WEBHOOK] No GELATO_WEBHOOK_SECRET set — skipping verification")
        return True

    expected = hmac.new(
        secret.encode("utf-8"),
        payload_bytes,
        hashlib.sha256,
    ).hexdigest()

    received = signature_header.split("=")[-1] if "=" in signature_header else signature_header
    return hmac.compare_digest(expected, received)


def list_supported_countries() -> list:
    """Return list of country codes where Gelato ships (known fulfillment zones)."""
    return ["US", "ES", "GB", "DE", "FR", "IT", "NL", "AU", "CA", "SE", "NO", "DK", "FI"]


# ---------------------------------------------------------------------------
# Shipping quote (real-time pricing)
# ---------------------------------------------------------------------------

_METHOD_NAMES = {
    "normal":   {"es": "Envío Estándar — Gelato", "en": "Standard Shipping — Gelato"},
    "express":  {"es": "Envío Express — Gelato",  "en": "Express Shipping — Gelato"},
    "standard": {"es": "Envío Estándar — Gelato", "en": "Standard Shipping — Gelato"},
    "overnight":{"es": "Envío Express — Gelato",  "en": "Express Shipping — Gelato"},
}

_METHOD_DAYS = {
    "normal":    {"es": "10-18 días hábiles", "en": "10-18 business days"},
    "express":   {"es": "5-10 días hábiles",  "en": "5-10 business days"},
    "standard":  {"es": "10-18 días hábiles", "en": "10-18 business days"},
    "overnight": {"es": "3-5 días hábiles",   "en": "3-5 business days"},
}

_PLACEHOLDER_PDF = "https://www.w3.org/WAI/WCAG21/Techniques/pdf/PDF2/tests/PDF2-chapter.pdf"

_FALLBACK_ADDRESS_BY_COUNTRY = {
    "US": {"country": "US", "city": "New York",   "postCode": "10001", "state": "NY",  "addressLine1": "123 Main St"},
    "ES": {"country": "ES", "city": "Madrid",     "postCode": "28001", "state": "MD",  "addressLine1": "Calle Mayor 1"},
    "GB": {"country": "GB", "city": "London",     "postCode": "W1A 1AA","state": "ENG","addressLine1": "1 Oxford St"},
    "DE": {"country": "DE", "city": "Berlin",     "postCode": "10115", "state": "BE",  "addressLine1": "Unter den Linden 1"},
    "FR": {"country": "FR", "city": "Paris",      "postCode": "75001", "state": "IDF", "addressLine1": "1 Rue de Rivoli"},
    "IT": {"country": "IT", "city": "Rome",       "postCode": "00100", "state": "RM",  "addressLine1": "Via del Corso 1"},
    "NL": {"country": "NL", "city": "Amsterdam",  "postCode": "1011 AB","state": "NH", "addressLine1": "Damrak 1"},
    "BE": {"country": "BE", "city": "Brussels",   "postCode": "1000",  "state": "BRU", "addressLine1": "Rue de la Loi 1"},
    "PT": {"country": "PT", "city": "Lisbon",     "postCode": "1100",  "state": "LSB", "addressLine1": "Rua Augusta 1"},
    "CH": {"country": "CH", "city": "Zurich",     "postCode": "8001",  "state": "ZH",  "addressLine1": "Bahnhofstrasse 1"},
    "AT": {"country": "AT", "city": "Vienna",     "postCode": "1010",  "state": "VIE", "addressLine1": "Stephansplatz 1"},
    "SE": {"country": "SE", "city": "Stockholm",  "postCode": "11120", "state": "AB",  "addressLine1": "Drottninggatan 1"},
    "NO": {"country": "NO", "city": "Oslo",       "postCode": "0150",  "state": "03",  "addressLine1": "Karl Johans gate 1"},
    "DK": {"country": "DK", "city": "Copenhagen", "postCode": "1050",  "state": "84",  "addressLine1": "Stroget 1"},
    "FI": {"country": "FI", "city": "Helsinki",   "postCode": "00100", "state": "01",  "addressLine1": "Aleksanterinkatu 1"},
    "PL": {"country": "PL", "city": "Warsaw",     "postCode": "00-001","state": "MZ",  "addressLine1": "ul. Krakowskie 1"},
    "IE": {"country": "IE", "city": "Dublin",     "postCode": "D01",   "state": "L",   "addressLine1": "O'Connell St 1"},
    "CA": {"country": "CA", "city": "Toronto",    "postCode": "M5V 3A8","state": "ON", "addressLine1": "100 King St W"},
    "AU": {"country": "AU", "city": "Sydney",     "postCode": "2000",  "state": "NSW", "addressLine1": "1 George St"},
    "NZ": {"country": "NZ", "city": "Auckland",   "postCode": "1010",  "state": "AUK", "addressLine1": "1 Queen St"},
    "JP": {"country": "JP", "city": "Tokyo",      "postCode": "100-0001","state": "13","addressLine1": "1 Chiyoda"},
    "KR": {"country": "KR", "city": "Seoul",      "postCode": "03000", "state": "11",  "addressLine1": "1 Jongno"},
    "BR": {"country": "BR", "city": "Sao Paulo",  "postCode": "01310-000","state": "SP","addressLine1": "Av. Paulista 1"},
}


def _get_draft_price(
    country_code: str,
    shipment_uid: str,
    currency: str = "USD",
    postal_code: str = None,
) -> Optional[float]:
    """
    Create a Gelato draft order and extract the total cost (print + shipping).
    Uses the customer's postal_code if provided for accuracy.
    Cancels the draft immediately after getting the price.
    Returns total cost in USD, or None on failure.
    """
    ref_id = f"QUOTE-{uuid.uuid4().hex[:10]}"
    addr_template = _FALLBACK_ADDRESS_BY_COUNTRY.get(country_code, {
        "country": country_code, "city": "Test City",
        "postCode": "00000", "state": "", "addressLine1": "1 Test St",
    })
    effective_postcode = postal_code or addr_template["postCode"]

    payload = {
        "orderType": "draft",
        "orderReferenceId": ref_id,
        "customerReferenceId": ref_id,
        "currency": currency,
        "items": [{
            "itemReferenceId": f"{ref_id}-1",
            "productUid": HC_A4_SKU,
            "quantity": 1,
            "pageCount": 30,
            "fileUrl": _PLACEHOLDER_PDF,
        }],
        "shipmentMethodUid": shipment_uid,
        "shippingAddress": {
            "firstName": "Quote",
            "lastName": "Request",
            "addressLine1": addr_template["addressLine1"],
            "city": addr_template["city"],
            "postCode": effective_postcode,
            "state": addr_template.get("state", ""),
            "country": addr_template["country"],
            "email": "quote@magicmemoriesbooks.com",
            "phone": "+10000000000",
        },
    }

    try:
        resp = requests.post(
            f"{GELATO_API_BASE}/v3/orders",
            headers=_headers(), json=payload, timeout=25,
        )
        if resp.status_code not in (200, 201):
            print(f"[GELATO QUOTE] Draft failed for {country_code}/{shipment_uid}: {resp.status_code} — {resp.text[:300]}")
            return None

        data = resp.json()
        order_id = data.get("id")
        # Debug log: show raw pricing fields so we can verify what Gelato returns
        print(f"[GELATO QUOTE DEBUG] {country_code}/{shipment_uid} raw keys: {list(data.keys())}")
        print(f"[GELATO QUOTE DEBUG] totalCost={data.get('totalCost')} price={data.get('price')} total={data.get('total')} billing={data.get('billing')}")
        items_raw = data.get("items", [])
        for _i in items_raw:
            print(f"[GELATO QUOTE DEBUG] item price={_i.get('price')} cost={_i.get('cost')} quantity={_i.get('quantity')}")
        total = _extract_total_from_order(data)

        if order_id:
            try:
                requests.delete(f"{GELATO_API_BASE}/v3/orders/{order_id}", headers=_headers(), timeout=10)
                print(f"[GELATO QUOTE] Draft {order_id} cancelled after pricing")
            except Exception:
                pass

        if total and total > 0:
            print(f"[GELATO QUOTE] {country_code}/{shipment_uid}: ${total:.2f}")
            return round(total, 2)

    except Exception as e:
        print(f"[GELATO QUOTE] Exception for {country_code}/{shipment_uid}: {e}")

    return None


def _extract_total_from_order(data: dict) -> Optional[float]:
    """
    Extract the total cost (print + shipping) from a Gelato v3 order response.

    Primary: sums 'price' from receipts[].items grouped by type:
      - type=product   → print cost
      - type=shipment  → shipping cost
      - type=packaging → packaging cost
    Fallback: reads item.price from the items array (print only, shipping=0).
    """
    # ── Primary: receipts breakdown ────────────────────────────────────────
    receipts = data.get("receipts") or []
    if receipts:
        print_cost = 0.0
        ship_cost = 0.0
        packaging_cost = 0.0
        found = False
        for receipt in receipts:
            for ri in receipt.get("items", []):
                try:
                    price = float(ri.get("price") or 0)
                except (TypeError, ValueError):
                    price = 0.0
                rtype = (ri.get("type") or "").lower()
                if rtype == "product":
                    print_cost += price
                    found = True
                elif rtype == "shipment":
                    ship_cost += price
                    found = True
                elif rtype == "packaging":
                    packaging_cost += price
        if found:
            total = print_cost + ship_cost + packaging_cost
            print(f"[GELATO QUOTE DEBUG] receipts → print={print_cost:.2f} ship={ship_cost:.2f} pkg={packaging_cost:.2f} total={total:.2f}")
            return round(total, 2)

    # ── Fallback: item.price (print cost only, no shipping) ────────────────
    items = data.get("items", [])
    item_cost = 0.0
    found_item = False
    for item in items:
        for field in ("price", "totalPrice", "cost"):
            val = item.get(field)
            if val is not None:
                try:
                    item_cost += float(val)
                    found_item = True
                    break
                except (TypeError, ValueError):
                    pass
    if found_item:
        print(f"[GELATO QUOTE DEBUG] fallback item.price → {item_cost:.2f} (shipping not captured)")
        return round(item_cost, 2)

    return None


def get_shipping_quote(
    country_code: str,
    currency: str = "USD",
    postal_code: str = None,
) -> dict:
    """
    Get real-time Gelato shipping options and costs for a given country.

    First attempts to use the Gelato /v3/shipment-methods endpoint.
    If that endpoint does not return pricing, falls back to creating
    draft orders (one per method) to get actual total costs (print + shipping).
    The customer's postal_code is used in draft orders when provided for accuracy.
    Draft orders are cancelled immediately after getting the price.

    Returns a dict keyed by shipmentMethodUid:
    {
        'express': {
            'name_es': str,
            'name_en': str,
            'days_es': str,
            'days_en': str,
            'gelato_cost': float,   # Gelato total charged (print + shipping)
        },
        ...
    }
    Returns empty dict if the country is not supported or the API fails.
    """
    # ── Step 1: /v3/shipment-methods — method availability + delivery days ONLY ──
    # IMPORTANT: the `price` field from this endpoint is shipping-only and does NOT
    # include the print cost. We never use it as gelato_cost. We only extract method
    # UIDs and delivery-day ranges here, then always fetch real totals via draft orders.
    try:
        resp = requests.get(
            f"{GELATO_API_BASE}/v3/shipment-methods",
            headers=_headers(),
            params={"country": country_code, "currency": currency, "productUid": HC_A4_SKU},
            timeout=15,
        )
        if resp.status_code == 200:
            raw_methods = resp.json().get("shipmentMethods", [])
            if raw_methods:
                method_uids = [
                    m.get("shipmentMethodUid") or m.get("uid")
                    for m in raw_methods
                    if m.get("shipmentMethodUid") or m.get("uid")
                ]
                method_uids = [u for u in method_uids if u][:3]  # limit to 3
                days_by_uid = {
                    (m.get("shipmentMethodUid") or m.get("uid")): (
                        m.get("minDeliveryDays", ""), m.get("maxDeliveryDays", "")
                    )
                    for m in raw_methods
                }
                print(f"[GELATO QUOTE] /shipment-methods: {len(method_uids)} method(s) for {country_code} — pricing via draft orders")
            else:
                method_uids = None
                days_by_uid = {}
        else:
            print(f"[GELATO QUOTE] /shipment-methods returned {resp.status_code} for {country_code}")
            method_uids = None
            days_by_uid = {}
    except Exception as e:
        print(f"[GELATO QUOTE] /shipment-methods error for {country_code}: {e}")
        method_uids = None
        days_by_uid = {}

    # ── Step 2: Fall back to draft orders for pricing ───────────────────────
    if method_uids is None:
        method_uids = ["express", "normal"]

    result = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=3) as pool:
        futures = {
            pool.submit(_get_draft_price, country_code, uid, currency, postal_code): uid
            for uid in method_uids
        }
        try:
            for future in concurrent.futures.as_completed(futures, timeout=40):
                uid = futures[future]
                try:
                    cost = future.result()
                    if cost and cost > 0:
                        min_d, max_d = days_by_uid.get(uid, ("", ""))
                        result[uid] = _build_option(uid, cost, min_d, max_d)
                except Exception as e:
                    print(f"[GELATO QUOTE] Draft future error for {uid}: {e}")
        except concurrent.futures.TimeoutError:
            print(f"[GELATO QUOTE] Draft-order futures timed out after 40s — returning partial results ({len(result)} options)")
            for future, uid in futures.items():
                if not future.done():
                    future.cancel()

    if result:
        print(f"[GELATO QUOTE] Draft-order pricing for {country_code} (postal: {postal_code or 'default'}): {list(result.keys())}")
    else:
        print(f"[GELATO QUOTE] Could not get pricing for {country_code}")

    return result


def _build_option(uid: str, cost: float, min_days=None, max_days=None) -> dict:
    """Build a shipping option dict for the checkout frontend."""
    names = _METHOD_NAMES.get(uid, {"es": f"{uid} — Gelato", "en": f"{uid} — Gelato"})
    if min_days and max_days:
        days_es = f"{min_days}-{max_days} días hábiles"
        days_en = f"{min_days}-{max_days} business days"
    else:
        default_days = _METHOD_DAYS.get(uid, {"es": "7-21 días hábiles", "en": "7-21 business days"})
        days_es = default_days["es"]
        days_en = default_days["en"]
    return {
        "name_es": names["es"],
        "name_en": names["en"],
        "days_es": days_es,
        "days_en": days_en,
        "gelato_cost": round(float(cost), 2),
    }
